#!/usr/bin/env bash
#
# e2e-local-setup.sh — point the Playwright e2e suite at a LOCAL Supabase.
#
# WHY THIS EXISTS. The e2e suite used to run against the PRODUCTION Supabase
# project. That (a) piled up thousands of throwaway auth sessions on prod — a
# real Disk-IO cost, see migration 037 — and (b) stops being acceptable the
# moment the app has real users. This gives the suite its own disposable
# database on your machine: no cloud project, no cost, no prod impact.
#
# WHAT IT DOES
#   1. Starts a TRIMMED local Supabase stack (skips the memory-heavy services
#      e2e doesn't need — Studio, the analytics pipeline, edge runtime, …).
#   2. Applies every migration in supabase/migrations to a clean DB.
#   3. Creates the dedicated Playwright test user (email pre-confirmed, no mail).
#   4. Writes .env.test (gitignored) pointing at the local stack.
#   5. Optionally runs the smoke spec to prove it works (pass --smoke).
#
# Re-runnable: every run resets the local DB and reseeds the user, so it always
# lands in a known-good state.
#
# PREREQS: Docker running, and the Supabase CLI (`supabase`) installed.
# Stop the stack (and free the RAM) when you're done:  supabase stop
#
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

# The dedicated test user. The email MUST contain e2e/test/playwright — that is
# what unlocks the litter-sweep guard in tests/e2e/global-setup.ts. Override via
# env if you like; the defaults are fine for a local throwaway account.
TEST_USER_EMAIL="${TEST_USER_EMAIL:-e2e@anchor.test}"
TEST_USER_PASSWORD="${TEST_USER_PASSWORD:-e2e-local-password}"

# Services e2e does NOT need. Excluding them roughly halves the stack's RAM —
# logflare+vector (the analytics pipeline) and studio are the big ones. e2e only
# needs Postgres + kong (gateway) + gotrue (auth) + postgrest (REST) + storage.
# If a future CLI rejects one of these names, drop it from the list; the full set
# is printed by `supabase start --help`.
EXCLUDE="studio,imgproxy,edge-runtime,logflare,vector,mailpit,supavisor,realtime"

command -v supabase >/dev/null || {
  echo "❌ Supabase CLI not found — install it: https://supabase.com/docs/guides/cli"; exit 1;
}
docker info >/dev/null 2>&1 || {
  echo "❌ Docker isn't running. Start Docker Desktop and re-run."; exit 1;
}

echo "▶ Starting local Supabase (trimmed: -x $EXCLUDE) …"
supabase start -x "$EXCLUDE"

echo "▶ Applying all migrations to a clean local DB (supabase db reset) …"
supabase db reset

# Read the local URL + keys straight from the running stack — never hardcoded,
# so this stays correct across CLI versions and any config.toml overrides.
eval "$(supabase status -o env)"
: "${API_URL:?supabase status did not report API_URL — is the stack up?}"
: "${ANON_KEY:?supabase status did not report ANON_KEY}"
: "${SERVICE_ROLE_KEY:?supabase status did not report SERVICE_ROLE_KEY}"

echo "▶ Creating the Playwright test user ($TEST_USER_EMAIL) …"
status="$(curl -s -o /dev/null -w '%{http_code}' -X POST "${API_URL}/auth/v1/admin/users" \
  -H "apikey: ${SERVICE_ROLE_KEY}" \
  -H "Authorization: Bearer ${SERVICE_ROLE_KEY}" \
  -H "Content-Type: application/json" \
  -d "{\"email\":\"${TEST_USER_EMAIL}\",\"password\":\"${TEST_USER_PASSWORD}\",\"email_confirm\":true}")"
case "$status" in
  2??) echo "  created." ;;
  422) echo "  already exists — reusing." ;;   # defensive; db reset normally clears it first
  *)   echo "❌ test-user creation failed (HTTP $status)"; exit 1 ;;
esac

echo "▶ Writing .env.test (gitignored) …"
if [ -f .env.test ]; then
  cp .env.test .env.test.bak
  echo "  backed up existing .env.test → .env.test.bak"
fi
cat > .env.test <<EOF
# Generated by scripts/e2e-local-setup.sh — points the e2e suite at your LOCAL
# Supabase stack. Gitignored. Re-run the script to regenerate.
NEXT_PUBLIC_SUPABASE_URL=${API_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SECRET_KEY=${SERVICE_ROLE_KEY}
TEST_USER_EMAIL=${TEST_USER_EMAIL}
TEST_USER_PASSWORD=${TEST_USER_PASSWORD}
EOF

echo "✅ Local e2e environment ready."
echo "   Run the suite:   pnpm e2e"
echo "   Stop the stack:  supabase stop"

if [ "${1:-}" = "--smoke" ]; then
  echo "▶ Running the smoke spec …"
  pnpm exec playwright test tests/e2e/smoke.spec.ts
fi
